### ISSUE TITLE
Move cookiecutter templates to their own repository

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/cubi-tk#96]
**Is your feature request related to a problem? Please describe.**
Having the ISA-tab cookiecutter templates inside of cubi-tk makes re-using them burdensome.

**Describe the solution you'd like**
Move them into a separate repository `cookiecutter-collection-cubi-isa-tab`. We should the usual convention of having one repository per cookiecutter here as we will always use them from within cubi-tk and not use them separately. Having one repository for each cookiecutter template too much overhead (for now).

cubi-tk should clone the current contents of the repository when being invoked with the templating command.

**Describe alternatives you've considered**
One could also clone the whole of cubi-tk and extract them where used but that is additional complexity.

**Additional context**
N/A

**Comment by mikkonie** [comment]
Note regarding the use of these templates:  The one part of the Python code I actually use when using these templates in external software is the [_TEMPLATES](https://github.com/bihealth/cubi-tk/blob/master/cubi_tk/isa_tpl/__init__.py#L96) mapping, which informs me of the currently available templates.

This or something like it should probably be included in the potential separate repository. Otherwise, any software using these templates would need to create their own boilerplate code for recognizing and describing available templates.

**Comment by eudesbarbosa** [comment]
Suggested first step: reorder `cubi_tk/isa_tpl/archive` - separate cookiecutter from config files.
